version: "3"

services:
  admin:
    container_name: admin
    restart: always
    build: ./backend/admin
    ports:
      - "3001:3001"
    networks:
      network_proyecto:
        aliases:
          - admin
  cliente:
    container_name: cliente
    restart: always
    build: ./backend/clientes
    ports:
      - "3002:3002"
    networks:
      network_proyecto:
        aliases:
          - cliente
  medico:
    container_name: medico
    restart: always
    build: ./backend/medicos
    ports:
      - "3003:3003"
    networks:
      network_proyecto:
        aliases:
          - medico
  secretaria:
    container_name: secretaria
    restart: always
    build: ./backend/secretaria
    ports:
      - "3004:3004"
    networks:
      network_proyecto:
        aliases:
          - secretaria
  sesion:
    container_name: sesion
    restart: always
    build: ./backend/sesion
    ports:
      - "3005:3005"
    networks:
      network_proyecto:
        aliases:
          - sesion
  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - admin
      - secretaria
      - sesion
      - medico
      - cliente
    networks:
      network_proyecto:
        aliases:
          - frontend
networks:
  network_proyecto:
    name: net_proyecto
    driver: bridge
    ipam: 
      driver: default